### ISSUE TITLE
Executing 'just distrobox-bazzite' gives an auth error

### ISSUE THREAD

**Issue by PDXPuma** [ublue-os/bazzite-arch#13]
On executing 'just distrobox-bazzite' starting on "Version: 38.20230820.0 (2023-08-20T10:11:37Z)" the following is returned:

```
[jeremy@fedora ~]$ just distrobox-bazzite
Creating Bazzite distrobox ...
Trying to pull ghcr.io/ublue-os/bazzite-arch-gnome:latest...
Error: initializing source docker://ghcr.io/ublue-os/bazzite-arch-gnome:latest: unable to retrieve auth token: invalid username/password: unauthorized
Check out the docs for exportable apps and instructions: https://github.com/ublue-os/bazzite-arch
```

This did not happen on the previous version , "Version: 38.20230818.0 (2023-08-20T00:05:35Z)"

Thanks!

**Comment by castrojo** [comment]
Ok the package is set to private but I don't know if that's on purpose for a reason so I'll defer to @KyleGospo and @EyeCantCU to decide, thanks for filing this!

**Comment by KyleGospo** [comment]
Mistake made in testing, this is now fixed.
