### ISSUE TITLE
After suspend / resume, Steam can't launch games: bwrap: Can't bind mount /oldroot/etc/resolv.conf on /newroot/etc/resolv.conf

### ISSUE THREAD

**Issue by ximGBu4cyQss5P** [ublue-os/bazzite-arch#15]
After a suspend / resume on my desktop or laptop, Steam from bazzite-arch can no longer launch games and I get an error like this.

bwrap: Can't bind mount /oldroot/etc/resolv.conf on /newroot/etc/resolv.conf: Unable to mount source on destination: No such file or directory

Host: Tumbleweed
Container: bazzite-arch
distrobox: 1.5.0.2-1.1 (RPM)
podman: 4.6.1-2.1
crun: 1.8.6-1.1

Container created like: `distrobox create --nvidia --image ghcr.io/ublue-os/bazzite-arch --name bazzite-arch --home ~/Containers/bazzite-arch`

The error message from Steam was helpful and it seemed like resolv.conf was bind mounted in the container, so when NetworkManager updated /etc/resolv.conf after resuming from sleep, for some reason bubblewrap is freaking out.

I poked around to see if I could disable bind mounting resolv.conf, and found the `--dns=none` parameter for podman-create. So I tried adding `--additional-flags "--dns=none"` to the distrobox create, but I get the same result.

Everything works perfectly until the system goes to sleep, then when it wakes up, games won't launch and I get the error above from Steam.  I'm probably just configuring something incorrectly, so any pointers would be appreciated.

**Comment by Dispatch9001** [comment]
I can confirm, I get this same issue on the uBlue `silverblue-nvidia` image. The temporary fix I was told on the Discord was to stop, remove and reinstall the container 
```
distrobox stop bazzite-arch
distrobox rm bazzite-arch
<use the distrobox command you installed it with>
```
This seems *slightly* impractical to do every time your laptop suspends.
