### ISSUE TITLE
Brawlhalla does not work inside of Bazzite-Arch

### ISSUE THREAD

**Issue by Tsubajashi** [ublue-os/bazzite-arch#19]
The game just closes as soon as the game has tried to start. Not even the EAC window is appearing. The Flatpak version of Steam doesnt seem to have this issue. Can someone verify that this issue is appearing on your side, too?

**Comment by KyleGospo** [comment]
Is this a Linux native game or a Windows title? If it's windows can you give me a proton log?

PROTON_LOG=1 %command%

**Comment by Tsubajashi** [comment]
a windows title.
https://paste.centos.org/view/8c2f7fb3

**Comment by Tsubajashi** [comment]
its also free, so it can be easily reproduced. doesnt matter which proton version is picked.

**Comment by Tsubajashi** [comment]
Another Update: Elden Ring doesnt seem to work on Bazzite-Arch either.

**Comment by KyleGospo** [comment]
You using Nvidia hardware?

**Comment by Tsubajashi** [comment]
yep, im using nvidia hardware
EAC Runtime is installed, i made sure to install it seperately beforehand

**Comment by KyleGospo** [comment]
Understood, we believe it's an issue with distrobox and Nvidia. It's being worked on right now

**Comment by Tsubajashi** [comment]
Thank you!

**Comment by Tsubajashi** [comment]
problem got solved, ill close this issue now :) thanks!
