### ISSUE TITLE
locale.gen error

### ISSUE THREAD

**Issue by Xdavius** [ublue-os/bazzite-arch#35]
Hi.

I have installed Lutris from bazzite-arch but the interface is in English (I want it in french, and all exported apps in french). I tried to locale-gen but unsuccessful.

```
davius@bazzite-arch:~$ sudo locale-gen
Generating locales...
  en_US.UTF-8... done
  fr_FR.UTF-8...failed to set locale!
[error] cannot open locale definition file `fr_FR': No such file or directory
```

**Comment by Xdavius** [comment]
update : 

commenting noextract in /etc/pacman.conf solve the issue but application still in english (lang not recognized ?)

**Comment by tj5miniop** [comment]
Try running locale -a on the container to see whether the locale you want is installed. 
If not, I'd reccomend looking at this - https://wiki.archlinux.org/title/Locale

**Comment by EyeCantCU** [comment]
Hi all. All locales supported by glibc are now integrated in the container. Thank you for raising an issue!
