### ISSUE TITLE
Source Game (Day of Defeat) gives a unable to find en_US.UTF-8

### ISSUE THREAD

**Issue by RedLanternTech** [ublue-os/bazzite-arch#36]
When I first start a game (Day of Defeat Source) it gives an error message stating it cannot find en_US.UTF-8.  It won't stop the game from playing but it comes up every time.  

The full Error is:
`SetLocale(en_US.UTF-8') failed.  Using 'C'. you may have limited glyph support.  Please install 'en_US.UTF-8 locale.`
 
![Screenshot from 2024-06-16 19-06-47](https://github.com/ublue-os/bazzite-arch/assets/91954742/6582c263-1a1e-4498-b24f-6a9eea79f972)

I was able to solve it by installing glibc-locales.  

I think it might be a good idea to add glibc-locales into the default install.  I resolved it at the moment by having a Distrobox Assembly file add it in for me if I tear down and rebuild the bazzite-arch container.   For Gnome, the full file looks like this
```
[Gaming-Gnome]
image=ghcr.io/ublue-os/bazzite-arch-gnome
home=~/conhome/gaming
aditional_packages="glibc-locales"
init=false
nvidia=true
pull=true
root=false
replace=true
unshare_netns=true
start_now=true
exported_apps="Steam"
exported_apps="Lutris"
exported_apps="protontricks"
```

Or if you are in the container `pacman -S glibc-locales`

**Comment by EyeCantCU** [comment]
Thanks for the report and fix! `glibc-locales` has been added :)
