### ISSUE TITLE
Signatures Error

### ISSUE THREAD

**Issue by juanchomann** [ublue-os/bazzite-arch#44]
on first install today:

`
Total Download Size:      1.34 MiB
Total Installed Size:  8375.01 MiB
Net Upgrade Size:      1193.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-setuptools-1:75.2.0-2-any downloading...
 python-charset-normalizer-3.4.0-1-any downloading...
 python-jaraco.collections-5.0.1-1-any downloading...
checking keyring...
checking package integrity...
error: python-jaraco.collections: signature from "Daniel M. Capella <polyzen@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/python-jaraco.collections-5.0.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: python-setuptools: signature from "Daniel M. Capella <polyzen@archlinux.org>" is unknown trust

:: File /var/cache/pacman/pkg/python-setuptools-1:75.2.0-2-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: python-charset-normalizer: signature from "Daniel M. Capella <polyzen@archlinux.org>" is unknown trust

:: File /var/cache/pacman/pkg/python-charset-normalizer-3.4.0-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)

Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred`

**Comment by catbabylon** [comment]
you just need to update keyrings separately before doing the full system update: 
`sudo pacman -Sy archlinux-keyring`

**Comment by juanchomann** [comment]
> you just need to update keyrings separately before doing the full system update: `sudo pacman -Sy archlinux-keyring`

Haven't done anything in it, this is the result of the fresh container using distrobox. 

i'll consider this as a fix for my environment.

**Comment by juanchomann** [comment]
I confirm it's working now.

![Image](https://github.com/user-attachments/assets/43e36f98-4cc8-41fa-98e4-3c5eab0e1df3)
